### ISSUE TITLE
jython-2.7-beta3/ broken pip, easy_install

### ISSUE THREAD

**Issue by rstormsf** [yyuu/pyenv#339] opened 2015-03-26 05:27 UTC
```
head -1 /Users/user/.pyenv/versions/jython-2.7-beta3/bin/pip
```
output:
```
#!/usr/bin/env \"/Users/user/.pyenv/versions/jython-2.7-beta3/bin/jython\"
```
`./pip`
produces:
```
env: \"/Users/user/.pyenv/versions/jython-2.7-beta3/bin/jython\": No such file or directory
```

**FIX**:

```
#!/usr/bin/env /Users/user/.pyenv/versions/jython-2.7-beta3/bin/jython
``` 
just removed quotes and backward slash at the env and front.

After I saved it and ran:
```
pip install pymongo
```
got this:
```
 *****************************************************

    The optional C extensions are currently not supported

    by this python implementation.

    *****************************************************
```

any idea?

**figured** that pymongo wants `cpython select module` which is not `jython` solution is to use `mongo.jar` driver :-)

**Comment by yyuu** [comment] 2015-03-28 16:28
I confirmed that the weird shebang line of `pip` with `jython-2.7-beta3` on OS X. Oddly I couldn't reproduce the issue on my Debian box :disappointed: Probably something wrong in `pip`'s installer script.

Basically this should be fixed in `pip` but it might be difficult since Jython 2.7 is still in development and not providing full feature `ssl` module, AFAIK.

`pymongo` issue is intrinsically the issue of the module itself. Nothing can be done from `pyenv`.

**Comment by joshfriend** [comment] 2015-05-05 04:47
Closing since jython-2.7.0 is at a final release version and the betas have been removed. (see #370)

**Closed by joshfriend** 2015-05-05 04:47 UTC
