### ISSUE TITLE
Issue with pyenv and vim plugin: E887: Sorry, this command is disabled

### ISSUE THREAD

**Issue by ianks** [yyuu/pyenv#234] opened 2014-09-10 16:21 UTC
When opening a file in vim, sometimes I get this error message:

```
Error detected while processing /Users/ianks/.yadr/vim/bundle/AutoTag/plugin/autotag.vim:

E887: Sorry, this command is disabled, the Python's site module could not be loaded.
```

Python is not my main language, but I have never had this issue with system Python. Any clues as to why this is happening?

**Comment by foxundermoon** [comment] 2015-01-05 09:14
you sure installed the python?
and must both 32bit  or  64bit, 
otherwise meet the error

**Comment by rene-aguirre** [comment] 2015-08-22 19:47
An actual solution, for those breaking vim/macvim after "brew cleanup".

This will work if the current python is not the one your current vim/gvim/mvim is not linked to, check your vim and macvim version info (these might be separate homebrew packages), also make sure you update our brew so you'd use the latest packages:

```
mvim --version
vim --version
```

You'd know what is the linked python library:

```
-L/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config
```
At this point that path is expected to be valid, hence the actual issue, In this case python `2.7.10_1` Cellar's is expected, now check your latest brew python package version:

```
brew info python
```

As you already confirmed the link path is valid (e.g. `ls /usr/local/Cellar/python/`), above command will show which is the active one, see top of output:

```
https://www.python.org
/usr/local/Cellar/python/2.7.10_2 (4943 files, 77M) *
...
```

Make sure python symlinks are fine:

```
brew unlink python && brew link --force python
```

And finally, re-build vim or macvim:

```
brew uninstall macvim && brew install macvim
```

Rebuilding is better than `brew install --force`, if you have the latest package, which I think is the case as that was the reason of a homebrew clean up.

Test your vim now

```
mvim --version
...
Compilation: ...
-L/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config
```

Now `:python print "hello"` should work on your mvim. Do the same for command line vim if required.

**Comment by yyuu** [comment] 2015-11-13 19:13
Feel free to reopen if there are still something need to be fixed in pyenv.

**Closed by yyuu** 2015-11-13 19:13 UTC
Labels: question

**Comment by bingtaoli** [comment] 2016-07-22 12:21
It is ok after reinstalling vim.
