### ISSUE TITLE
Failed to install pypy 3 on OS X

### ISSUE THREAD

**Issue by ssbb** [yyuu/pyenv#573] opened 2016-04-09 11:02 UTC
OS: OS X El Capitan 10.11.4 (15E65)
Pyenv: pyenv 20160303-57-gd594bca

```
➜  ~ pyenv install pypy3-2.4.0                                                                                                                                                                system
Downloading pypy3-2.4.0-osx64.tar.bz2...
-> https://bitbucket.org/pypy/pypy/downloads/pypy3-2.4.0-osx64.tar.bz2
Installing pypy3-2.4.0-osx64...
ERROR: invalid Python executable: /Users/ssbb/.pyenv/versions/pypy3-2.4.0/bin/python

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/yyuu/pyenv/issues

BUILD FAILED (OS X 10.11.4 using python-build 20160303-57-gd594bca)

Inspect or clean up the working tree at /var/folders/7q/6zlg21z952l8rr4kzgfd7_n40000gn/T/python-build.20160409175937.72618
Results logged to /var/folders/7q/6zlg21z952l8rr4kzgfd7_n40000gn/T/python-build.20160409175937.72618.log

Last 10 log lines:
/var/folders/7q/6zlg21z952l8rr4kzgfd7_n40000gn/T/python-build.20160409175937.72618 ~
/var/folders/7q/6zlg21z952l8rr4kzgfd7_n40000gn/T/python-build.20160409175937.72618/pypy3-2.4.0-osx64 /var/folders/7q/6zlg21z952l8rr4kzgfd7_n40000gn/T/python-build.20160409175937.72618 ~
```

**Comment by yyuu** [comment] 2016-04-15 00:56
It works at least for me.

```
% pyenv install -v pypy3-2.4.0
/var/folders/rc/_9kglbjs651431bbh2736s300000gn/T/python-build.20160415095109.1922 ~
Downloading pypy3-2.4.0-osx64.tar.bz2...
-> https://bitbucket.org/pypy/pypy/downloads/pypy3-2.4.0-osx64.tar.bz2
/var/folders/rc/_9kglbjs651431bbh2736s300000gn/T/python-build.20160415095109.1922/pypy3-2.4.0-osx64 /var/folders/rc/_9kglbjs651431bbh2736s300000gn/T/python-build.20160415095109.1922 ~
Installing pypy3-2.4.0-osx64...
Installing pip from https://bootstrap.pypa.io/get-pip.py...
Collecting pip
  Downloading pip-8.1.1-py2.py3-none-any.whl (1.2MB)
Collecting setuptools
  Downloading setuptools-20.7.0-py2.py3-none-any.whl (508kB)
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-8.1.1 setuptools-20.7.0 wheel-0.29.0
/var/folders/rc/_9kglbjs651431bbh2736s300000gn/T/tmpdlxfq7/pip.zip/pip/_vendor/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
/var/folders/rc/_9kglbjs651431bbh2736s300000gn/T/python-build.20160415095109.1922 ~
~
Installed pypy3-2.4.0-osx64 to /Users/yyuu/.pyenv/versions/pypy3-2.4.0

% pyenv shell pypy3-2.4.0
% python --version
Python 3.2.5 (b2091e973da6, Oct 19 2014, 18:30:58)
[PyPy 2.4.0 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)]
```

@ssbb please check if installation of other PyPy versions work or not.

**Comment by kgtekito** [comment] 2016-04-26 04:31
The same happened for me during installation of python 3.5.0.
`% pyenv install 3.5.0Downloading Python-3.5.0.tgz...
-> https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tgz
Installing Python-3.5.0...
ERROR: invalid Python executable: /Users/kgtekito/$HOME/.pyenv/versions/3.5.0/bin/python3.5

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/yyuu/pyenv/issues

BUILD FAILED (OS X 10.11.2 using python-build 20160130)

Inspect or clean up the working tree at /var/folders/pc/qm0mkfpd0qd1r92gmt31_2wc0000gp/T/python-build.20160426132201.83559
Results logged to /var/folders/pc/qm0mkfpd0qd1r92gmt31_2wc0000gp/T/python-build.20160426132201.83559.log

Last 10 log lines:
                        install|*) ensurepip="" ;; \
                esac; \
                 ./python.exe -E -m ensurepip \
                        $ensurepip --root=/ ; \
        fi
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-7.1.2 setuptools-18.2
`

**Comment by yyuu** [comment] 2016-05-02 00:22
The cause of installation failure of PyPy (except `pypy*-src`) and CPython must be totally different since former is binary distribution. Please don't mix up different things.

Because I could not reproduce the issue, I'll just close this. Please let me know if there's still *PyPy* installation failures occurring for you.

**Closed by yyuu** 2016-05-02 00:22 UTC
Labels: question

**Comment by andrew-christianson** [comment] 2018-05-02 04:51
@ssbb quite a bit later, but: did you happen to have `--enable-framework` in `PYTHON_CONFIGURE_OPTIONS` when this happened?

**Comment by ryan-williams** [comment] 2018-06-10 00:08
I thought I had this problem; turns out there are some `BUILD FAILED` messages but pypy3 is actually installed!

Check `pyenv versions` (or the return code of the `pyenv install` cmd) to verify…
