### ISSUE TITLE
Dynamically imported files don't have pyenv in path

### ISSUE THREAD

**Issue by DakotaNelson** [yyuu/pyenv#415] opened 2015-07-26 21:42 UTC
In one of my projects, I'm calling the following code:

```python
currentDir = os.path.dirname(os.path.abspath(__file__))
encodersDir = os.path.join(currentDir, 'encoders')
encoders = pkgutil.iter_modules(path=[encodersDir])
encoderNames = [modName for _,modName,_ in encoders]
# then, later
moduleName = '.'.join(['encoders', encoderName])
importlib.import_module(moduleName)
```

However, when the module is imported, it appears that pyenv isn't added to the path of the new module.

When I run python by itself, it detects pyenv and all is well:
```
[dnelson@blueharvest somedir]$ python
Python 2.7 (r27:82500, Jun  1 2015, 15:01:57) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux3
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.getsitepackages()
['/home/dnelson/.pyenv/versions/2.7/lib/python2.7/site-packages', '/home/dnelson/.pyenv/versions/2.7/lib/site-python']
>>> site.PREFIXES
['/home/dnelson/.pyenv/versions/2.7', '/home/dnelson/.pyenv/versions/2.7']
>>> 
```

When I run the same code inside the module that is dynamically imported:

```
['/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages', '/usr/lib/site-python']
['/usr', '/usr']
```

It appears that modules imported dynamically from within user python don't have the pyenv shimming added. This is causing `ImportError: No module named x` for any non-system import within the dynamically imported module.

**Comment by yyuu** [comment] 2015-08-02 10:08
I tried, but I couldn't reproduced.

```
% cat <<EOS >showsitepackages.py
#!/usr/bin/env python
from __future__ import print_function
import site
print(repr(site.getsitepackages()))
EOS
% pyenv version
2.7.10 (set by PYENV_VERSION environment variable)
% python showsitepackages.py
['/home/yyuu/.pyenv/versions/2.7.10/lib/python2.7/site-packages', '/home/yyuu/.pyenv/versions/2.7.10/lib/site-python']
% python -c 'import importlib; importlib.import_module("showsitepackages")'
['/home/yyuu/.pyenv/versions/2.7.10/lib/python2.7/site-packages', '/home/yyuu/.pyenv/versions/2.7.10/lib/site-python']
```

**Comment by yyuu** [comment] 2015-09-22 03:38
I close this for now since I couldn't reproduce it. Feel free to reopen if you still have problem.

**Closed by yyuu** 2015-09-22 03:38 UTC
Labels: question

**Comment by jcdrubay** [comment] 2020-11-05 11:31
Hi,

I am also facing this issue and it was also reported here:

https://stackoverflow.com/a/31643758

There is a easy workaround, but a fix would be welcome :)
