### ISSUE TITLE
Not working with Python 3.3.6 on Ubuntu trusty/64

### ISSUE THREAD

**Issue by Alex3917** [yyuu/pyenv#363] opened 2015-04-19 21:27 UTC
I'm getting an error when using pip to install psycopg2 that it can't find the Python.h file, which normally means that the ubuntu python-dev package isn't installed. In this case though there isn't a python-dev package for python3.3 on trusty/64, so I'm wondering what I need install manually in order to get this functionality. For reference, here is the relevant section from my ansible file:

```
---
...
- name: Install requirements.txt
  pip: requirements={{ app_path }}/requirements.txt virtualenv={{ pyenv_path }}/my_env
```

**Comment by blueyed** [comment] 2015-04-19 22:27
Ubuntu Trusty has 3.4.0-0ubuntu2 as python3 (for python3-dev). python3.3-dev only exists for Ubuntu Saucy.

But psycopg2 should use your pyenv's python, right?

Is your "Install requirements.txt" task failing?

You need to make the psycopg2 build use your .pyenv/versions/.../include/*/Python.h file.

There should be no need to install python3-dev, in case you use pyenv only.

The problem is likely that `pip` is not used from from your `virtualenv` (pyenv): you need to set the `executable` option to your pyenv's pip ([ref](http://docs.ansible.com/pip_module.html)).

**Comment by Alex3917** [comment] 2015-04-20 03:26
Thanks so much! Adding the executable parameter worked, at least once I got pip installed into the virtualenv.

**Comment by blueyed** [comment] 2015-04-20 05:41
You're welcome, I'm glad I could help - I am closing the issue.

This made me look into Ansible finally a bit more.. :)
(first stop: better indenting support in Vim for it (https://github.com/chase/vim-ansible-yaml/pull/36) ;))

I'd be interested in any snippets you come up with to improve pyenv with Ansible etc.

**Closed by blueyed** 2015-04-20 05:41 UTC
